spring:
  cloud:
    gateway:
      default-filters:

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
